version: '3'

services:
  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-api
    ports:
      - 3030:3000
    container_name: ecommerce-api
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 3030
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: m.farhat@hykaia.com
networks:
  default:
    external:
      name: nginx-proxy

